n1 = int(input("Enter number 1: "))
n2 = int(input("Enter number 2: "))
n3 = int(input("Enter number 3: "))
n4 = int(input("Enter number 4: "))
n5 = int(input("Enter number 5: "))
print("Arithmetic mean of the 5 numbers: ", (n1+n2+n3+n4+n5)/5)